server:
  port: 2333
  adress: "0.0.0.0"
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: true
    bufferDurationMs: 400
    youtubeConfig:
      playlistLoadLimit: 6
    ws:
      endpoint: "/v4/websocket"
